### ISSUE TITLE
New 1.4 release

### ISSUE THREAD

**Issue by arthurvr** [tastejs/todomvc#1362]
Lately we discussed doing a new TodoMVC release and agreed to open an issue to discuss what we want to finish. :star2: 

This would be my list:
- [ ] https://github.com/tastejs/todomvc/issues/1110 - Finish porting all apps over to the new UI so they're at least all consistent when doing a release. We're almost done, though :smiley: 
- [x] https://github.com/tastejs/todomvc/issues/1222 - I feel like we can't really ship with a main app totally broken.
- [x] https://github.com/tastejs/todomvc/issues/1069 - There's already an open PR and it's kind of a shame we're at such an ancient Ember version.
- [x] https://github.com/tastejs/todomvc/issues/1342 - Polymer just had its first major release and is much discussed lately so I think it might be a good idea for us to ship with a 1.0 example.
- [ ] https://github.com/tastejs/todomvc/issues/845 - with the overload of frameworks there are I think it's beneficial to go over them and see if we can drop some. Also because of this overload of frameworks, having "recommendations" is something people really want and ask for.

That's it for me at least.

Also we have https://github.com/tastejs/todomvc/issues/1259 which makes the new layout look ugly on Firefox. I feel like it's a firefox bug so we should just wait till they fix it but on the other hand it's really, really ugly :cry:

**Comment by arthurvr** [comment]
@tastejs/todomvc

**Comment by passy** [comment]
That sounds like a reasonable list. Thanks for putting this together, @arthurvr! :star2:

**Comment by passy** [comment]
I've updated the milestone for 1.4 with those issues: https://github.com/tastejs/todomvc/milestones/1.4

**Comment by samccone** [comment]
I would like to include

* [ ] Integrate automated perf testing via https://github.com/samccone/leaky

**Comment by arthurvr** [comment]
@samccone Can you open an individual issue discussing that? I'm totally :+1:, but we only discussed that much in hangouts so worth having it in the open.

**Comment by addyosmani** [comment]
Agreed. This is an excellent list. Thanks @arthurvr!

**Comment by CrowdHailer** [comment]
Some review or recommendation feature would be really helpful. Probably best if its not open comments as there are enough places for that already. Would love opinions from a todoMVC maintainer or two next to each one. Obviously thats extra work so maybe another way. I am happy to volunteer my own comments on a few but letting anyone (i.e. me) do that leads quickly to it being a long list of comments

**Comment by FadySamirSadek** [comment]
closed in favor of tracking in V1.5 milestone
