### ISSUE TITLE
Drop the ExtJS + DeftJS app

### ISSUE THREAD

**Issue by arthurvr** [tastejs/todomvc#1714]
The project seems poorly maintained, the app isn't spec compliant by far, and nobody in the community seems eager to maintain the example app. Everybody alright with (at least temporary) getting rid of it? :)

**Comment by arthurvr** [comment]
We had a very brief discussion about this on hangouts: we'd like to find someone to refresh the example as we still think it might be interesting to keep around for a little longer.

**Comment by arthurvr** [comment]
Small list of things that need updating:

* [ ] Editing should be cancelled when pressing escape (https://github.com/tastejs/todomvc/issues/789)
* [ ] Switch to npm
* [ ] Update to the new UI
* [ ] Focus on the new item field on load (https://github.com/tastejs/todomvc/issues/1029)
* [ ] Implement routing and remove the mark from `index.html` (#812)
* [ ] Make sure all tests pass and remove all `knownIssues.js` entries

Assigning @addyosmani as he was planning to look for someone to give the app an update. Might make sense to just contact someone from Sencha?

**Comment by Fruitseller** [comment]
@arthurvr  Do you still want to maintain this project? I briefly looked into the DeftJS [repo](https://github.com/deftjs/DeftJS) and it wasn't maintained since 2014.

**Comment by FadySamirSadek** [comment]
@Fruitseller  my vote is to remove it if you want you can submit a PR to remove it from examples folder and from the site homepage

**Comment by Fruitseller** [comment]
@FadySamirSadek Thank you for your response. The PR is a good idea and I will start with it.
